/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import db.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
/**
 *
 * @author Oscar Josue
 */
public class ClienteForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClienteForm.class.getName());

    String rol;
    String nombre;
    
    public ClienteForm(String rolRecibido, String nombreRecibido) {
  initComponents();
  mostrarClientes();
  this.rol = rolRecibido;
  this.nombre = nombreRecibido;
  this.setLocationRelativeTo(null);
    }
    
public void mostrarClientes() {
   DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("ID");
    modelo.addColumn("Nombre");
    modelo.addColumn("Apellido"); // AGREGADO: Para que coincida con el INSERT
    modelo.addColumn("Telefono");
    modelo.addColumn("Correo");
    modelo.addColumn("Direccion");

    tblClientes.setModel(modelo);

    // Usamos try-with-resources para que la conexión se cierre SOLA al terminar
    // Esto evita que el programa se congele por exceso de conexiones abiertas
    try (Connection con = Conexion.conectar();
         Statement st = con.createStatement();
         ResultSet rs = st.executeQuery("SELECT * FROM Cliente")) {

        while (rs.next()) {
            Object[] fila = new Object[6]; // Tamaño 6 (del 0 al 5)
            fila[0] = rs.getInt("id_cliente");
            fila[1] = rs.getString("nombre");
            fila[2] = rs.getString("apellido"); // AGREGADO
            fila[3] = rs.getString("telefono");
            fila[4] = rs.getString("correo");
            fila[5] = rs.getString("direccion");

            modelo.addRow(fila);
        }

    } catch (Exception e) {
        // e.printStackTrace() ayuda a ver el error real en la consola de abajo
        e.printStackTrace(); 
        JOptionPane.showMessageDialog(null, "Error al mostrar: " + e.getMessage());
    }
}

public void limpiarCampos(){ 
    txtId.setText(""); 
    txtNombre.setText("");
    txtApellido.setText(""); 
    txtTelefono.setText(""); 
    txtCorreo.setText(""); 
    txtDireccion.setText("");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        txtTelefono = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnModificar1 = new javax.swing.JButton();
        txtCorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTION DE CLIENTES");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 144, -1));

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Telefono", "Direccion"
            }
        ));
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 550, 470));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(85, 85, 85));
        jLabel6.setText("Buscar:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 70, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(85, 85, 85));
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 80, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(85, 85, 85));
        jLabel1.setText("Apellido:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 80, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(85, 85, 85));
        jLabel3.setText("Correo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 80, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(85, 85, 85));
        jLabel4.setText("Direccion:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 80, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestión De Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 30));
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 630, 30));
        jPanel2.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 630, 30));

        btnSalir.setBackground(new java.awt.Color(178, 59, 59));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 140, 40));

        btnEliminar.setBackground(new java.awt.Color(234, 234, 234));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(51, 51, 51));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 150, 40));

        btnGuardar.setBackground(new java.awt.Color(44, 44, 44));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 140, 40));
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 630, 30));
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 630, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(44, 44, 44));
        jLabel9.setText("ELEGANCE STORE");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 210, -1));

        btnModificar1.setBackground(new java.awt.Color(234, 234, 234));
        btnModificar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnModificar1.setForeground(new java.awt.Color(51, 51, 51));
        btnModificar1.setText("MODIFICAR");
        btnModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 140, 40));
        jPanel2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 630, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 670, 470));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/mapequeño.png"))); // NOI18N
        jLabel7.setText("jLabel4");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 120, 70));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logo_elegance_store_300x125.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 360, 260));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(85, 85, 85));
        jLabel10.setText("Id:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 70, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(85, 85, 85));
        jLabel5.setText("Telefono:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 80, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1610, 920));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
    DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("ID");
    modelo.addColumn("Nombre");
    modelo.addColumn("Telefono");
    modelo.addColumn("Correo");
    modelo.addColumn("Direccion");

    tblClientes.setModel(modelo);

    try {
        Connection con = Conexion.conectar();
        PreparedStatement ps = con.prepareStatement(
            "SELECT * FROM Cliente WHERE nombre LIKE ?"
        );

        ps.setString(1, "%" + txtBuscar.getText() + "%");

        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            Object[] fila = new Object[5];
            fila[0] = rs.getInt("id_cliente");
            fila[1] = rs.getString("nombre");
            fila[2] = rs.getString("telefono");
            fila[3] = rs.getString("correo");
            fila[4] = rs.getString("direccion");

            modelo.addRow(fila);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
int fila = tblClientes.getSelectedRow();
    
    // Validamos que realmente haya una fila seleccionada
    if (fila != -1) {
        txtId.setText(tblClientes.getValueAt(fila, 0).toString());       
        txtNombre.setText(tblClientes.getValueAt(fila, 1).toString());    
        txtApellido.setText(tblClientes.getValueAt(fila, 2).toString());  
        txtTelefono.setText(tblClientes.getValueAt(fila, 3).toString());
        txtCorreo.setText(tblClientes.getValueAt(fila, 4).toString());
        txtDireccion.setText(tblClientes.getValueAt(fila, 5).toString());
    }
    }//GEN-LAST:event_tblClientesMouseClicked

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
      // Abrimos el menú enviando de nuevo los datos del usuario
    // (Luego podemos hacer que estos datos sean dinámicos)
    MenuPrincipal menu = new MenuPrincipal(this.rol, this.nombre); 
    menu.setVisible(true);
    menu.setLocationRelativeTo(null);
    
    // Cerramos la ventana actual de Clientes
    this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    try {
        Connection con = Conexion.conectar();

        String sql = "DELETE FROM Cliente WHERE id_cliente=?";
        PreparedStatement ps = con.prepareStatement(sql);

        ps.setInt(1, Integer.parseInt(txtId.getText()));

        ps.executeUpdate();

        JOptionPane.showMessageDialog(null, "Cliente eliminado");

        mostrarClientes();
        limpiarCampos();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    
    if (txtNombre.getText().isEmpty() || txtTelefono.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, llene los campos obligatorios.");
        return;
    }

    // Declaramos la conexión fuera para poder cerrarla después
    Connection con = null;

    try {
        // 2. Intentar conectar
        con = Conexion.conectar();
        
        // --- ERROR RESUELTO AQUÍ: VALIDACIÓN DE NULO ---
        if (con == null) {
            JOptionPane.showMessageDialog(null, "ERROR: No hay conexión con MySQL.\nVerifica si XAMPP está encendido.");
            return; // Salimos del método para que no intente usar "con"
        }

        // 3. Preparar SQL
        String sql = "INSERT INTO Cliente (id_cliente, nombre, apellido, telefono, correo, direccion) VALUES (?, ?, ?, ?, ?, ?)";
        PreparedStatement ps = con.prepareStatement(sql);

        ps.setInt(1, Integer.parseInt(txtId.getText()));
        ps.setString(2, txtNombre.getText());
        ps.setString(3, txtApellido.getText());
        ps.setString(4, txtTelefono.getText());
        ps.setString(5, txtCorreo.getText());
        ps.setString(6, txtDireccion.getText());

        // 4. Ejecutar
        ps.executeUpdate();
        JOptionPane.showMessageDialog(null, "¡Cliente guardado exitosamente!");

        // 5. Refrescar y Limpiar
        mostrarClientes();
        limpiarCampos();

    } catch (Exception e) {
        e.printStackTrace(); // Esto te dirá el error real en la consola de abajo
        JOptionPane.showMessageDialog(null, "Error al guardar: " + e.getMessage());
    } finally {
        // --- ERROR RESUELTO AQUÍ: CIERRE DE CONEXIÓN ---
        try {
            if (con != null) con.close(); 
        } catch (SQLException ex) {
            System.out.println("Error al cerrar conexión: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar1ActionPerformed
    try {
    Connection con = Conexion.conectar();

    // El SQL tiene 7 signos de interrogación (6 para los datos nuevos y 1 para el WHERE)
    String sql = "UPDATE Cliente SET id_cliente=?, nombre=?, apellido=?, telefono=?, correo=?, direccion=? WHERE id_cliente=?";
    PreparedStatement ps = con.prepareStatement(sql);

    // Los 6 datos que se van a actualizar
    ps.setInt(1, Integer.parseInt(txtId.getText()));
    ps.setString(2, txtNombre.getText());
    ps.setString(3, txtApellido.getText());
    ps.setString(4, txtTelefono.getText());
    ps.setString(5, txtCorreo.getText());
    ps.setString(6, txtDireccion.getText());

    // --- EL QUE TE FALTABA: El parámetro número 7 para el WHERE ---
    ps.setInt(7, Integer.parseInt(txtId.getText())); 

    ps.executeUpdate();

    JOptionPane.showMessageDialog(null, "Cliente actualizado exitosamente");

    mostrarClientes();
    limpiarCampos();
    
    // IMPORTANTE: No olvides cerrar la conexión
    con.close();

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error al actualizar: " + e.getMessage());
}
    }//GEN-LAST:event_btnModificar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
