/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Oscar Josue
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
   // Agrega estas dos variables arriba del constructor para guardar los datos
String rol;
String nombre;

public MenuPrincipal(String rolRecibido, String nombreRecibido) { // <--- Ahora recibe datos
    initComponents();
    this.rol = rolRecibido;
    this.nombre = nombreRecibido;
    
// Lógica inteligente para el mensaje
    if (this.rol.equalsIgnoreCase("Admin") || this.rol.equalsIgnoreCase("Administrador")) {
        // Si es jefe, sale en verde
        lblRolActual.setText("En línea: Administrador - " + nombre);
        lblRolActual.setForeground(java.awt.Color.GREEN);
    } else {
        // Si es trabajador, sale en azul (o el color que prefieras)
        lblRolActual.setText("En línea: Trabajador - " + nombre);
        lblRolActual.setForeground(java.awt.Color.CYAN); 
    }
    
    restringirPermisos();
}

private void restringirPermisos() {
    if (this.rol.equals("Trabajador") || this.rol.equals("Empleado")) {
        // Deshabilitamos los botones que solo el Admin debe usar
        btnUsuarios.setEnabled(false); // No puede crear otros usuarios
        
        // Si quieres que ni siquiera vea el botón, usa:
        // btnUsuarios.setVisible(false);
        
        // Puedes agregar más botones aquí, por ejemplo:
        // btnConfiguracion.setEnabled(false);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProductos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        lblRolActual = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU PRINCIPAL");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProductos.setBackground(new java.awt.Color(31, 31, 31));
        btnProductos.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnProductos.setText("PRODUCTO");
        btnProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(46, 46, 46)));
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        getContentPane().add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 210, 40));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ELEGANCE STORE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 220, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENÚ PRINCIPAL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 180, -1));

        btnCerrarSesion.setBackground(new java.awt.Color(31, 31, 31));
        btnCerrarSesion.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("CERRAR SESIÓN");
        btnCerrarSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(46, 46, 46)));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 670, 210, 40));

        btnClientes.setBackground(new java.awt.Color(31, 31, 31));
        btnClientes.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes.setText("CLIENTE");
        btnClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(46, 46, 46)));
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 210, 40));

        btnInventario.setBackground(new java.awt.Color(31, 31, 31));
        btnInventario.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnInventario.setForeground(new java.awt.Color(255, 255, 255));
        btnInventario.setText("INVENTARIO");
        btnInventario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(46, 46, 46)));
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, 210, 40));

        btnUsuarios.setBackground(new java.awt.Color(31, 31, 31));
        btnUsuarios.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setText("USUARIO");
        btnUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(46, 46, 46)));
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 610, 210, 40));

        lblRolActual.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblRolActual.setForeground(new java.awt.Color(51, 255, 0));
        getContentPane().add(lblRolActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 410, 510, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/elegance.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 0, 1650, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
// PASO CLAVE: Le pasamos el rol y nombre que guardamos en este Menú
    ClienteForm ventanaClientes = new ClienteForm(this.rol, this.nombre); 
    
    ventanaClientes.setVisible(true);
    ventanaClientes.setLocationRelativeTo(null);
    
    this.dispose(); // Cerramos el menú     // TODO add your handling code here:
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
// 1. Preguntar al usuario para evitar cierres accidentales
    int respuesta = javax.swing.JOptionPane.showConfirmDialog(this, 
            "¿Está seguro que desea cerrar la sesión?", 
            "Confirmar Salida", 
            javax.swing.JOptionPane.YES_NO_OPTION);

    if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
        // 2. Crear e iniciar la ventana de Login
        LoginFrom login = new LoginFrom(); 
        login.setVisible(true);
        login.setLocationRelativeTo(null); // Centrar la ventana

        // 3. Destruir la ventana actual del Menú
        this.dispose();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
// 1. Creamos la instancia del formulario de Productos
    // Pasamos 'this.rol' y 'this.nombre' que ya existen en el Menú
    ProductoForm proForm = new ProductoForm(this.rol, this.nombre);
    
    // 2. Lo hacemos visible
    proForm.setVisible(true);
    
    // 3. Lo centramos en la pantalla
    proForm.setLocationRelativeTo(null);
    
    // 4. Cerramos (o escondemos) el Menú para que no se amontonen las ventanas
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
    InventarioForm invForm = new InventarioForm(this.rol, this.nombre);
    
    // 2. Lo hacemos visible
    invForm.setVisible(true);
    
    // 3. Lo centramos en la pantalla
    invForm.setLocationRelativeTo(null);
    
    // 4. Cerramos (o escondemos) el Menú para que no se amontonen las ventanas
    this.dispose(); 
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
 // 1. Creamos la instancia del formulario de Usuarios
  UsuarioForm userForm = new UsuarioForm(this.rol, this.nombre);

// 2. Lo hacemos visible
userForm.setVisible(true);

// 3. Lo centramos en la pantalla
userForm.setLocationRelativeTo(null);

// 4. (Opcional) Cerramos o minimizamos el menú actual
 this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblRolActual;
    // End of variables declaration//GEN-END:variables
}
