/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Oscar Josue
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
   // Agrega estas dos variables arriba del constructor para guardar los datos
String rol;
String nombre;

public MenuPrincipal(String rolRecibido, String nombreRecibido) { // <--- Ahora recibe datos
    initComponents();
    this.rol = rolRecibido;
    this.nombre = nombreRecibido;
    
// Lógica inteligente para el mensaje
    if (this.rol.equalsIgnoreCase("Admin") || this.rol.equalsIgnoreCase("Administrador")) {
        // Si es jefe, sale en verde
        lblRolActual.setText("En línea: Administrador - " + nombre);
        lblRolActual.setForeground(java.awt.Color.GREEN);
    } else {
        // Si es trabajador, sale en azul (o el color que prefieras)
        lblRolActual.setText("En línea: Trabajador - " + nombre);
        lblRolActual.setForeground(java.awt.Color.CYAN); 
    }
    
    restringirPermisos();
}

private void restringirPermisos() {
    // Usamos equalsIgnoreCase para evitar errores por mayúsculas/minúsculas
    if (this.rol.equalsIgnoreCase("Trabajador") || this.rol.equalsIgnoreCase("Empleado")) {
        
        // Bloqueamos Reportes (Bitácora)
        btnReportes.setEnabled(false); 
        
        // Bloqueamos Gestión de Usuarios
        btnUsuarios.setEnabled(false); 
        
        // OPCIONAL: Si prefieres que ni siquiera aparezcan los botones:
        // btnReportes.setVisible(false);
        // btnUsuarios.setVisible(false);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRolActual = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnClientes = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU PRINCIPAL");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRolActual.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblRolActual.setForeground(new java.awt.Color(51, 255, 0));
        getContentPane().add(lblRolActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 510, 30));

        jPanel1.setBackground(new java.awt.Color(0, 31, 107));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MENU PRINCIPAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ELEGANCE STORE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        btnClientes.setBackground(new java.awt.Color(31, 31, 31));
        btnClientes.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes.setText("CLIENTE");
        btnClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(46, 46, 46)));
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jPanel1.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 210, 40));

        btnInventario.setBackground(new java.awt.Color(31, 31, 31));
        btnInventario.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnInventario.setForeground(new java.awt.Color(255, 255, 255));
        btnInventario.setText("INVENTARIO");
        btnInventario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(46, 46, 46)));
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 210, 40));

        btnProductos.setBackground(new java.awt.Color(31, 31, 31));
        btnProductos.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnProductos.setText("PRODUCTO");
        btnProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(46, 46, 46)));
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        jPanel1.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 210, 40));

        btnReportes.setBackground(new java.awt.Color(31, 31, 31));
        btnReportes.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("REPORTES");
        btnReportes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(46, 46, 46)));
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        jPanel1.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 210, 40));

        btnCerrarSesion.setBackground(new java.awt.Color(31, 31, 31));
        btnCerrarSesion.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("CERRAR SESIÓN");
        btnCerrarSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(46, 46, 46)));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 210, 40));

        btnUsuarios.setBackground(new java.awt.Color(31, 31, 31));
        btnUsuarios.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setText("USUARIO");
        btnUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(46, 46, 46)));
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 210, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 510, 480));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/aelegante.jpeg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-340, -120, -1, 970));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
 registrarAccion("El usuario " + this.nombre + " entró a Gestión de Clientes");       
// PASO CLAVE: Le pasamos el rol y nombre que guardamos en este Menú
    ClienteForm ventanaClientes = new ClienteForm(this.rol, this.nombre); 
    
    ventanaClientes.setVisible(true);
    ventanaClientes.setLocationRelativeTo(null);
    
    this.dispose(); // Cerramos el menú     // TODO add your handling code here:
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
// 1. Preguntar al usuario para evitar cierres accidentales
    int respuesta = javax.swing.JOptionPane.showConfirmDialog(this, 
            "¿Está seguro que desea cerrar la sesión?", 
            "Confirmar Salida", 
            javax.swing.JOptionPane.YES_NO_OPTION);

    if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
        // 2. Crear e iniciar la ventana de Login
        LoginFrom login = new LoginFrom(); 
        login.setVisible(true);
        login.setLocationRelativeTo(null); // Centrar la ventana

        // 3. Destruir la ventana actual del Menú
        this.dispose();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
     registrarAccion("El usuario " + this.nombre + " entró a Gestión de Productos");
    
    ProductoForm pro = new ProductoForm(this.rol, this.nombre);
    pro.setVisible(true);
    this.dispose();
    // 4. Cerramos (o escondemos) el Menú para que no se amontonen las ventanas
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
    registrarAccion("El usuario " + this.nombre + " entró a Inventario");
    InventarioForm invForm = new InventarioForm(this.rol, this.nombre);
    
    // 2. Lo hacemos visible
    invForm.setVisible(true);
    
    // 3. Lo centramos en la pantalla
    invForm.setLocationRelativeTo(null);
    
    // 4. Cerramos (o escondemos) el Menú para que no se amontonen las ventanas
    this.dispose(); 
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
    registrarAccion("Consultó el historial de movimientos");
    
    ReportesForm repo = new ReportesForm(this.rol, this.nombre);
    repo.setVisible(true);
    repo.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
// 1. Registramos la acción
    registrarAccion("El usuario " + this.nombre + " entró a Gestión de Usuarios");
    
    // 2. Abrimos la ventana de Usuarios (pasando los datos de sesión)
    UsuarioForm userForm = new UsuarioForm(this.rol, this.nombre);
    userForm.setVisible(true);
    userForm.setLocationRelativeTo(null);
    
    // 3. Cerramos el menú
    this.dispose();     
    }//GEN-LAST:event_btnUsuariosActionPerformed

    // MÉTODO PARA LA BITÁCORA (Cópialo y pégalo aquí)
    public void registrarAccion(String accion) {
        String sql = "INSERT INTO bitacora (usuario, rol, accion) VALUES (?, ?, ?)";
        db.Conexion dbCon = new db.Conexion(); 
        
        try (java.sql.Connection con = dbCon.conectar(); 
             java.sql.PreparedStatement ps = con.prepareStatement(sql)) {
            
            if (con != null) {
                ps.setString(1, this.nombre); // Usa el nombre que ya tiene el Menú
                ps.setString(2, this.rol);    // Usa el rol que ya tiene el Menú
                ps.setString(3, accion);
                ps.executeUpdate();
            }
        } catch (java.sql.SQLException e) {
            System.out.println("Error en bitácora: " + e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblRolActual;
    // End of variables declaration//GEN-END:variables
}
