/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.InventarioDAO;
import java.sql.Connection;          // Para establecer la conexión
import java.sql.PreparedStatement;   // Para ejecutar las consultas SQL
import java.sql.ResultSet;           // Para recibir datos de la base de datos (al listar)
import java.sql.SQLException;        // Para manejar errores de SQL
import java.util.ArrayList;          // Para guardar la lista de productos
import java.util.List;               // Para el método de ListarProductos
import model.Producto;               // Tu clase modelo que acabas de crear
import db.Conexion;
import javax.swing.JOptionPane;
import dao.ProductoDAO;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Oscar Josue
 */
public class ProductoForm extends javax.swing.JFrame {
    
    String rol;
    String nombre;
    ProductoDAO proDao = new ProductoDAO();
    InventarioDAO invDao = new InventarioDAO();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProductoForm.class.getName());

    private void LimpiarCampos() {
    txtId.setText("");
    txtNombre.setText("");
    txtMarca.setText("");
    txtCategoria.setText("");
    txtTalla.setText("");
    txtPrecio.setText("");
    txtEntrada.setText("");
    txtSalida.setText("");
}
    
    public void registrarAccion(String accion) {
    String sql = "INSERT INTO bitacora (usuario, rol, accion) VALUES (?, ?, ?)";
    db.Conexion dbCon = new db.Conexion(); 
    
    try (java.sql.Connection con = dbCon.conectar(); 
         java.sql.PreparedStatement ps = con.prepareStatement(sql)) {
        
        if (con != null) {
            ps.setString(1, this.nombre); // Nombre del usuario logueado
            ps.setString(2, this.rol);    // Rol del usuario logueado
            ps.setString(3, accion);
            ps.executeUpdate();
        }
    } catch (java.sql.SQLException e) {
        System.out.println("Error en bitácora: " + e.getMessage());
    }
}
    
    public void ListarProductos() {
    List<Producto> ListarPro = proDao.ListarProductos();
    DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();
    
    // Limpiar la tabla antes de cargar los nuevos datos
    modelo.setRowCount(0); 
    
    Object[] ob = new Object[8]; // Son 8 columnas
    for (int i = 0; i < ListarPro.size(); i++) {
        ob[0] = ListarPro.get(i).getId();
        ob[1] = ListarPro.get(i).getNombre();
        ob[2] = ListarPro.get(i).getMarca();
        ob[3] = ListarPro.get(i).getCategoria();
        ob[4] = ListarPro.get(i).getTalla();
        ob[5] = ListarPro.get(i).getPrecio();
        ob[6] = ListarPro.get(i).getEntrada();
        ob[7] = ListarPro.get(i).getSalida();
        modelo.addRow(ob);
    }
    tblProductos.setModel(modelo);
}
    
    /**
     * Creates new form ProductoForm
     */
    public ProductoForm(String rolRecibido, String nombreRecibido) {
    initComponents();
    this.rol = rolRecibido;
    this.nombre = nombreRecibido;
    this.setLocationRelativeTo(null);
    ListarProductos();
    
       
        if (this.rol.equalsIgnoreCase("Admin") || this.rol.equalsIgnoreCase("Administrador")) {
        // Si es jefe, sale en verde
        lblRolActual.setText("En línea: Administrador - " + nombre);
        lblRolActual.setForeground(java.awt.Color.GREEN);
    } else {
        // Si es trabajador, sale en azul (o el color que prefieras)
        lblRolActual.setText("En línea: Trabajador - " + nombre);
        lblRolActual.setForeground(java.awt.Color.CYAN); 
    }
    
     restringirPermisos();
    }
    
          private void restringirPermisos() {
    if (this.rol.equals("Trabajador") || this.rol.equals("Empleado")) {
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        txtCategoria = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        txtTalla = new javax.swing.JTextField();
        txtSalida = new javax.swing.JTextField();
        txtEntrada = new javax.swing.JTextField();
        btnEliminar1 = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblRolActual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTION DE PRODUCTOS");

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 144, -1));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Marca", "Categoria", "Talla", "Precio", "Entrada", "Salida"
            }
        ));
        tblProductos.setSelectionBackground(new java.awt.Color(212, 175, 55));
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 550, 570));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(85, 85, 85));
        jLabel6.setText("Buscar:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 70, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(85, 85, 85));
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 80, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(85, 85, 85));
        jLabel1.setText("Marca:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 80, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(85, 85, 85));
        jLabel3.setText("Talla:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 80, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(85, 85, 85));
        jLabel4.setText("Precio:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 80, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestión De Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.setEditable(false);
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 30));
        jPanel2.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 630, 30));
        jPanel2.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 630, 30));

        btnSalir.setBackground(new java.awt.Color(178, 59, 59));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, 140, 40));

        btnGuardar.setBackground(new java.awt.Color(44, 44, 44));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 140, 40));
        jPanel2.add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 630, 30));
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 630, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(44, 44, 44));
        jLabel9.setText("ELEGANCE STORE");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 210, -1));

        btnModificar.setBackground(new java.awt.Color(234, 234, 234));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(51, 51, 51));
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 140, 40));
        jPanel2.add(txtTalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 630, 30));
        jPanel2.add(txtSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 630, 30));
        jPanel2.add(txtEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 630, 30));

        btnEliminar1.setBackground(new java.awt.Color(234, 234, 234));
        btnEliminar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar1.setForeground(new java.awt.Color(51, 51, 51));
        btnEliminar1.setText("ELIMINAR");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 150, 40));

        btnLimpiar.setBackground(new java.awt.Color(234, 234, 234));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(51, 51, 51));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 140, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 670, 590));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(85, 85, 85));
        jLabel10.setText("Id:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 70, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(85, 85, 85));
        jLabel5.setText("Categoria:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 80, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(85, 85, 85));
        jLabel11.setText("Salida:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, 80, 20));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(85, 85, 85));
        jLabel12.setText("Entrada:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 80, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/mapequeño.png"))); // NOI18N
        jLabel8.setText("jLabel4");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 120, 70));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/mapequeño.png"))); // NOI18N
        jLabel7.setText("jLabel4");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 680, 120, 70));

        lblRolActual.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblRolActual.setForeground(new java.awt.Color(51, 255, 0));
        jPanel1.add(lblRolActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 540, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1622, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1616, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 926, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
// 1. Obtenemos lo que el usuario escribió
    String texto = txtBuscar.getText();
    
    // 2. Llamamos al DAO para que nos traiga la lista filtrada
    List<Producto> lista = proDao.BuscarProducto(texto);
    
    // 3. Llenamos la tabla con esa nueva lista
    DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();
    modelo.setRowCount(0);
    Object[] ob = new Object[8];
    for (int i = 0; i < lista.size(); i++) {
        ob[0] = lista.get(i).getId();
        ob[1] = lista.get(i).getNombre();
        ob[2] = lista.get(i).getMarca();
        ob[3] = lista.get(i).getCategoria();
        ob[4] = lista.get(i).getTalla();
        ob[5] = lista.get(i).getPrecio();
        ob[6] = lista.get(i).getEntrada();
        ob[7] = lista.get(i).getSalida();
        modelo.addRow(ob);
    }       
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
// 1. Identificar qué fila se tocó
    int fila = tblProductos.rowAtPoint(evt.getPoint());

    // 2. Pasar los datos de la tabla a los JTextFields
    txtId.setText(tblProductos.getValueAt(fila, 0).toString());
    txtNombre.setText(tblProductos.getValueAt(fila, 1).toString());
    txtMarca.setText(tblProductos.getValueAt(fila, 2).toString());
    txtCategoria.setText(tblProductos.getValueAt(fila, 3).toString());
    txtTalla.setText(tblProductos.getValueAt(fila, 4).toString());
    txtPrecio.setText(tblProductos.getValueAt(fila, 5).toString());
    txtEntrada.setText(tblProductos.getValueAt(fila, 6).toString());
    txtSalida.setText(tblProductos.getValueAt(fila, 7).toString());
    }//GEN-LAST:event_tblProductosMouseClicked

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
// 1. Creamos la instancia del Menú Principal
    // Le pasamos las variables que este formulario ya tiene guardadas
    MenuPrincipal menu = new MenuPrincipal(this.rol, this.nombre);
    
    // 2. Configuramos la ventana del Menú
    menu.setVisible(true);
    menu.setLocationRelativeTo(null); // Para que salga centrado
    
    // 3. Cerramos la ventana actual de Productos
    this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
    txtId.setText("");
    txtNombre.setText("");
    txtMarca.setText("");
    txtCategoria.setText("");
    txtTalla.setText("");
    txtPrecio.setText("");
    txtEntrada.setText("");
    txtSalida.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
 try {
    // 1. Capturamos los datos del nuevo producto
    model.Producto pro = new model.Producto();
    // Nota: El ID no se setea aquí porque suele ser Autoincrementable en la BD
    pro.setNombre(txtNombre.getText());
    pro.setMarca(txtMarca.getText());
    pro.setCategoria(txtCategoria.getText());
    pro.setTalla(txtTalla.getText());
    pro.setPrecio(Double.parseDouble(txtPrecio.getText()));
    
    int entrada = Integer.parseInt(txtEntrada.getText());
    int salida = Integer.parseInt(txtSalida.getText());
    pro.setEntrada(entrada);
    pro.setSalida(salida);

    // 2. Ejecutamos el registro en la tabla Producto
    // Importante: Usamos registrarProducto (o como se llame tu método de insert)
    if (proDao.registrarProducto(pro)) { 

        // --- LÓGICA DE FILA ÚNICA PARA EL INVENTARIO ---
        model.Inventario inv = new model.Inventario();
        
        // Recuperamos el ID que la base de datos le asignó al nuevo producto
        // Si tu método registrarProducto no devuelve el ID, asegúrate de obtenerlo
        int idRecienCreado = proDao.obtenerUltimoId(); 
        inv.setId_producto(idRecienCreado);
        
        inv.setUbicacion("BODEGA CENTRAL");
        
        // GUARDAMOS LA ENTRADA EN 'CANTIDAD' (Para que se vea el 4)
        inv.setCantidad(entrada); 

        // EL TIPO SE DEFINE POR EL RESULTADO NETO
        // Para que al listar podamos hacer la resta (Entrada - Salida)
        if (entrada >= salida) {
            inv.setTipo("ENTRADA");
        } else {
            inv.setTipo("SALIDA");
        }
        
        // Registramos UNA SOLA FILA en el historial
        invDao.RegistrarInventario(inv); 
        // -----------------------------------------------

        JOptionPane.showMessageDialog(null, "✔️ Producto guardado e Inventario registrado"); 
        ListarProductos(); 
        LimpiarCampos();
    } else {
        JOptionPane.showMessageDialog(null, "❌ Error al guardar el producto");
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error: Verifique los datos numéricos");
    System.out.println(e.toString());
}
        registrarAccion("Guardo el producto: " + txtNombre.getText());   
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
if (txtId.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Seleccione una fila");
    } else {
        try {
            // 2. Definimos las variables que te salían en rojo
            int id = Integer.parseInt(txtId.getText());
            String nombre = txtNombre.getText();
            String marca = txtMarca.getText();
            String cat = txtCategoria.getText();
            String talla = txtTalla.getText();
            double precio = Double.parseDouble(txtPrecio.getText());
            int entrada = Integer.parseInt(txtEntrada.getText());
            int salida = Integer.parseInt(txtSalida.getText());

            // 3. Llenamos el objeto Producto
            model.Producto pro = new model.Producto();
            pro.setId(id);
            pro.setNombre(nombre);
            pro.setMarca(marca);
            pro.setCategoria(cat);
            pro.setTalla(talla);
            pro.setPrecio(precio);
            pro.setEntrada(entrada);
            pro.setSalida(salida);

            // 4. Ejecutamos la modificación
            if (proDao.modificarProducto(pro)) {
                
                // --- LÓGICA DE FILA ÚNICA PARA EL INVENTARIO ---
                model.Inventario inv = new model.Inventario();
                inv.setId_producto(id); // Ya no saldrá en rojo
                inv.setUbicacion("BODEGA CENTRAL");
                inv.setCantidad(entrada); 

                if (entrada >= salida) {
                    inv.setTipo("ENTRADA");
                } else {
                    inv.setTipo("SALIDA");
                }

                // Esto dejará de estar en rojo cuando hagas el paso 2 abajo
                invDao.ActualizarInventario(inv); 
                // -----------------------------------------------

                JOptionPane.showMessageDialog(null, "✔️ Producto e Inventario actualizados"); 
                ListarProductos(); 
                LimpiarCampos();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: Verifique los datos");
        }
    }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
if (!"".equals(txtId.getText())) {
    int pregunta = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar este producto y todo su historial de inventario?");
    
    if (pregunta == 0) { // 0 significa que el usuario hizo clic en "SÍ"
        try {
            int id = Integer.parseInt(txtId.getText());

            // 1. PRIMER PASO: Borrar de la tabla 'inventario'
            // Esto elimina todos los registros de cantidad y ubicación de este producto
            if (invDao.EliminarInventarioPorProducto(id)) {
                
                // 2. SEGUNDO PASO: Borrar de la tabla 'producto'
                if (proDao.eliminarProducto(id)) {
                    JOptionPane.showMessageDialog(null, "✔️ Producto e historial eliminados correctamente");
                    
                    // Registro opcional en bitácora si lo usas
                    // registrarAccion("El usuario " + this.nombre + " eliminó el producto ID: " + id);
                    
                    LimpiarCampos();
                    ListarProductos();
                } else {
                    JOptionPane.showMessageDialog(null, "❌ Error al eliminar el producto de la tabla principal");
                }
                
            } else {
                JOptionPane.showMessageDialog(null, "❌ No se pudo limpiar el historial del inventario");
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error: El ID no es válido.");
        }
    }
} else {
    JOptionPane.showMessageDialog(null, "Seleccione un producto de la tabla para eliminar");
}
    registrarAccion("Eliminó el producto: " + txtNombre.getText());
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRolActual;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtEntrada;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtSalida;
    private javax.swing.JTextField txtTalla;
    // End of variables declaration//GEN-END:variables
}
