/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.Connection;          // Para establecer la conexión
import java.sql.PreparedStatement;   // Para ejecutar las consultas SQL
import java.sql.ResultSet;           // Para recibir datos de la base de datos (al listar)
import java.sql.SQLException;        // Para manejar errores de SQL
import java.util.ArrayList;          // Para guardar la lista de productos
import java.util.List;               // Para el método de ListarProductos
import model.Producto;               // Tu clase modelo que acabas de crear
import db.Conexion;
import javax.swing.JOptionPane;
import dao.ProductoDAO;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Oscar Josue
 */
public class ProductoForm extends javax.swing.JFrame {
    
    ProductoDAO proDao = new ProductoDAO();
    String rol;
    String nombre;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProductoForm.class.getName());

    private void LimpiarCampos() {
    txtId.setText("");
    txtNombre.setText("");
    txtMarca.setText("");
    txtCategoria.setText("");
    txtTalla.setText("");
    txtPrecio.setText("");
    txtEntrada.setText("");
    txtSalida.setText("");
}
    
    public void ListarProductos() {
    List<Producto> ListarPro = proDao.ListarProductos();
    DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();
    
    // Limpiar la tabla antes de cargar los nuevos datos
    modelo.setRowCount(0); 
    
    Object[] ob = new Object[8]; // Son 8 columnas
    for (int i = 0; i < ListarPro.size(); i++) {
        ob[0] = ListarPro.get(i).getId();
        ob[1] = ListarPro.get(i).getNombre();
        ob[2] = ListarPro.get(i).getMarca();
        ob[3] = ListarPro.get(i).getCategoria();
        ob[4] = ListarPro.get(i).getTalla();
        ob[5] = ListarPro.get(i).getPrecio();
        ob[6] = ListarPro.get(i).getEntrada();
        ob[7] = ListarPro.get(i).getSalida();
        modelo.addRow(ob);
    }
    tblProductos.setModel(modelo);
}
    
    /**
     * Creates new form ProductoForm
     */
    public ProductoForm(String rolRecibido, String nombreRecibido) {
    initComponents();
    this.rol = rolRecibido;
    this.nombre = nombreRecibido;
    this.setLocationRelativeTo(null);
    ListarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        txtCategoria = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnModificar1 = new javax.swing.JButton();
        txtTalla = new javax.swing.JTextField();
        txtSalida = new javax.swing.JTextField();
        txtEntrada = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTION DE PRODUCTOS");

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 144, -1));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Marca", "Categoria", "Talla", "Precio", "Entrada", "Salida"
            }
        ));
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 550, 570));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(85, 85, 85));
        jLabel6.setText("Buscar:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 70, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(85, 85, 85));
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 80, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(85, 85, 85));
        jLabel1.setText("Marca:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 80, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(85, 85, 85));
        jLabel3.setText("Talla:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 80, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(85, 85, 85));
        jLabel4.setText("Precio:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 80, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestión De Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 30));
        jPanel2.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 630, 30));
        jPanel2.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 630, 30));

        btnSalir.setBackground(new java.awt.Color(178, 59, 59));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, 140, 40));

        btnEliminar.setBackground(new java.awt.Color(234, 234, 234));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(51, 51, 51));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 150, 40));

        btnGuardar.setBackground(new java.awt.Color(44, 44, 44));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 140, 40));
        jPanel2.add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 630, 30));
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 630, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(44, 44, 44));
        jLabel9.setText("ELEGANCE STORE");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 210, -1));

        btnModificar1.setBackground(new java.awt.Color(234, 234, 234));
        btnModificar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnModificar1.setForeground(new java.awt.Color(51, 51, 51));
        btnModificar1.setText("MODIFICAR");
        btnModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, 140, 40));
        jPanel2.add(txtTalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 630, 30));
        jPanel2.add(txtSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 630, 30));
        jPanel2.add(txtEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 630, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 670, 560));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(85, 85, 85));
        jLabel10.setText("Id:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 70, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(85, 85, 85));
        jLabel5.setText("Categoria:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 80, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(85, 85, 85));
        jLabel11.setText("Salida:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, 80, 20));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(85, 85, 85));
        jLabel12.setText("Entrada:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 80, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/mapequeño.png"))); // NOI18N
        jLabel8.setText("jLabel4");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 120, 70));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/mapequeño.png"))); // NOI18N
        jLabel7.setText("jLabel4");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 660, 120, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1622, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1616, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 926, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
// 1. Obtenemos lo que el usuario escribió
    String texto = txtBuscar.getText();
    
    // 2. Llamamos al DAO para que nos traiga la lista filtrada
    List<Producto> lista = proDao.BuscarProducto(texto);
    
    // 3. Llenamos la tabla con esa nueva lista
    DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();
    modelo.setRowCount(0);
    Object[] ob = new Object[8];
    for (int i = 0; i < lista.size(); i++) {
        ob[0] = lista.get(i).getId();
        ob[1] = lista.get(i).getNombre();
        ob[2] = lista.get(i).getMarca();
        ob[3] = lista.get(i).getCategoria();
        ob[4] = lista.get(i).getTalla();
        ob[5] = lista.get(i).getPrecio();
        ob[6] = lista.get(i).getEntrada();
        ob[7] = lista.get(i).getSalida();
        modelo.addRow(ob);
    }       
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
// 1. Identificar qué fila se tocó
    int fila = tblProductos.rowAtPoint(evt.getPoint());

    // 2. Pasar los datos de la tabla a los JTextFields
    txtId.setText(tblProductos.getValueAt(fila, 0).toString());
    txtNombre.setText(tblProductos.getValueAt(fila, 1).toString());
    txtMarca.setText(tblProductos.getValueAt(fila, 2).toString());
    txtCategoria.setText(tblProductos.getValueAt(fila, 3).toString());
    txtTalla.setText(tblProductos.getValueAt(fila, 4).toString());
    txtPrecio.setText(tblProductos.getValueAt(fila, 5).toString());
    txtEntrada.setText(tblProductos.getValueAt(fila, 6).toString());
    txtSalida.setText(tblProductos.getValueAt(fila, 7).toString());
    }//GEN-LAST:event_tblProductosMouseClicked

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
// 1. Creamos la instancia del Menú Principal
    // Le pasamos las variables que este formulario ya tiene guardadas
    MenuPrincipal menu = new MenuPrincipal(this.rol, this.nombre);
    
    // 2. Configuramos la ventana del Menú
    menu.setVisible(true);
    menu.setLocationRelativeTo(null); // Para que salga centrado
    
    // 3. Cerramos la ventana actual de Productos
    this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
if (!txtId.getText().isEmpty()) {
        // Preguntar al usuario si está seguro
        int pregunta = JOptionPane.showConfirmDialog(null, "¿Estás seguro de eliminar este producto?");
        
        if (pregunta == 0) { // 0 significa "SÍ"
            int id = Integer.parseInt(txtId.getText());
            
            if (proDao.EliminarProducto(id)) {
                JOptionPane.showMessageDialog(null, "Producto eliminado correctamente");
                LimpiarCampos();   // Para vaciar los cuadros
                ListarProductos(); // Para que desaparezca de la tabla de inmediato
            }
        }
    } else {
        JOptionPane.showMessageDialog(null, "Selecciona un producto de la tabla primero");
    }  
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
// 1. Primero validamos que los campos básicos no estén vacíos
    if (!txtNombre.getText().isEmpty() && !txtPrecio.getText().isEmpty()) {
        
        try {
            Producto pro = new Producto();
            ProductoDAO proDao = new ProductoDAO();

            // 2. Capturamos los textos normales
            pro.setNombre(txtNombre.getText());
            pro.setMarca(txtMarca.getText());
            pro.setCategoria(txtCategoria.getText());
            pro.setTalla(txtTalla.getText());

        
            String precioTexto = txtPrecio.getText().replace(",", ".");
            pro.setPrecio(Double.parseDouble(precioTexto));
            // ------------------------------------

            // 3. Capturamos los números enteros (Entrada y Salida)
            pro.setEntrada(Integer.parseInt(txtEntrada.getText()));
            pro.setSalida(Integer.parseInt(txtSalida.getText()));

            // 4. Mandamos a guardar al DAO
            if (proDao.registrarProducto(pro)) {
                JOptionPane.showMessageDialog(null, "¡Producto guardado con éxito!");
                LimpiarCampos();
                ListarProductos();
                
                // Aquí puedes llamar a un método para limpiar los campos
            }

        } catch (NumberFormatException e) {
            // Este error sale si el usuario escribe letras donde van números
            JOptionPane.showMessageDialog(null, "Error: En Precio, Entrada y Salida solo se permiten números.");
        }
        
    } else {
        JOptionPane.showMessageDialog(null, "Por favor llena los campos obligatorios.");
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar1ActionPerformed
if (txtId.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Selecciona un producto de la tabla");
    } else {
        if (!txtNombre.getText().isEmpty() && !txtPrecio.getText().isEmpty()) {
            Producto pro = new Producto();
            
            // Llenamos el objeto con los datos de los cuadros de texto
            pro.setId(Integer.parseInt(txtId.getText()));
            pro.setNombre(txtNombre.getText());
            pro.setMarca(txtMarca.getText());
            pro.setCategoria(txtCategoria.getText());
            pro.setTalla(txtTalla.getText());
            
            String precioTexto = txtPrecio.getText().replace(",", ".");
            pro.setPrecio(Double.parseDouble(precioTexto));
            pro.setEntrada(Integer.parseInt(txtEntrada.getText()));
            pro.setSalida(Integer.parseInt(txtSalida.getText()));

            if (proDao.ModificarProducto(pro)) {
                JOptionPane.showMessageDialog(null, "¡Producto modificado!");
                LimpiarCampos();
                ListarProductos(); // Para que se vea el cambio en la tabla
            }
        }
    }  
    }//GEN-LAST:event_btnModificar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtEntrada;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtSalida;
    private javax.swing.JTextField txtTalla;
    // End of variables declaration//GEN-END:variables
}
