/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.UsuarioDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Usuario;

/**
 *
 * @author Oscar Josue
 */
public class UsuarioForm extends javax.swing.JFrame {
    
    String nombre;
    String rol;
    
Usuario u = new Usuario();
UsuarioDAO uDao = new UsuarioDAO();
DefaultTableModel modelo = new DefaultTableModel();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UsuarioForm.class.getName());

    /**
     * Creates new form UsuarioForm
     */
    public UsuarioForm(String rolRecibido, String nombreRecibido) {
        initComponents();
        ListarUsuarios();
        this.rol = rolRecibido;
        this.nombre = nombreRecibido;
        this.setLocationRelativeTo(null);
        
           
        if (this.rol.equalsIgnoreCase("Admin") || this.rol.equalsIgnoreCase("Administrador")) {
        // Si es jefe, sale en verde
        lblRolActual.setText("En línea: Administrador - " + nombre);
        lblRolActual.setForeground(java.awt.Color.GREEN);
    } else {
        // Si es trabajador, sale en azul (o el color que prefieras)
        lblRolActual.setText("En línea: Trabajador - " + nombre);
        lblRolActual.setForeground(java.awt.Color.CYAN); 
    }
    
     restringirPermisos();
    }
    
          private void restringirPermisos() {
    if (this.rol.equals("Trabajador") || this.rol.equals("Empleado")) {
    }
}
          
          public void registrarAccion(String accion) {
    String sql = "INSERT INTO bitacora (usuario, rol, accion) VALUES (?, ?, ?)";
    db.Conexion dbCon = new db.Conexion(); 
    
    try (java.sql.Connection con = dbCon.conectar(); 
         java.sql.PreparedStatement ps = con.prepareStatement(sql)) {
        
        if (con != null) {
            ps.setString(1, this.nombre); 
            ps.setString(2, this.rol);    
            ps.setString(3, accion);
            ps.executeUpdate();
        }
    } catch (java.sql.SQLException e) {
        System.out.println("Error en bitácora: " + e.getMessage());
    }
}
    
    public void ListarUsuarios() {
    List<Usuario> lista = uDao.ListarUsuarios();
    modelo = (DefaultTableModel) tblUsuarios.getModel();
    modelo.setRowCount(0); // Limpia la tabla para que no se dupliquen los datos
    Object[] ob = new Object[5];
    for (int i = 0; i < lista.size(); i++) {
        ob[0] = lista.get(i).getIdUsuario();
        ob[1] = lista.get(i).getNombreCompleto();
        ob[2] = lista.get(i).getUsername();
        ob[3] = lista.get(i).getContrasena();
        ob[4] = lista.get(i).getRol();
        modelo.addRow(ob);
    }
    tblUsuarios.setModel(modelo);
}
    
    public void LimpiarCampos() {
    txtId.setText("");
    txtNombre_Completo.setText("");
    txtUsername.setText("");
    txtContrasena.setText("");
    txtRol.setText("");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtRol = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        txtContrasena = new javax.swing.JTextField();
        txtNombre_Completo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnModificar1 = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblRolActual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTION DE USUARIOS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 144, -1));

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre_Completo", "Username", "Contraseña", "Rol"
            }
        ));
        tblUsuarios.setSelectionBackground(new java.awt.Color(212, 175, 55));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 550, 470));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(85, 85, 85));
        jLabel6.setText("Buscar:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 70, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(85, 85, 85));
        jLabel2.setText("Nombre_Completo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(85, 85, 85));
        jLabel1.setText("Username:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 110, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(85, 85, 85));
        jLabel4.setText("Rol:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 80, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestión De Usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.setEditable(false);
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 30));
        jPanel2.add(txtRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 630, 30));
        jPanel2.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 630, 30));

        btnSalir.setBackground(new java.awt.Color(178, 59, 59));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 140, 40));

        btnEliminar.setBackground(new java.awt.Color(234, 234, 234));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(51, 51, 51));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 150, 40));

        btnGuardar.setBackground(new java.awt.Color(44, 44, 44));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 140, 40));
        jPanel2.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 630, 30));
        jPanel2.add(txtNombre_Completo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 630, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(44, 44, 44));
        jLabel9.setText("ELEGANCE STORE");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 210, -1));

        btnModificar1.setBackground(new java.awt.Color(234, 234, 234));
        btnModificar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnModificar1.setForeground(new java.awt.Color(51, 51, 51));
        btnModificar1.setText("MODIFICAR");
        btnModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 140, 40));

        btnEliminar1.setBackground(new java.awt.Color(234, 234, 234));
        btnEliminar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar1.setForeground(new java.awt.Color(51, 51, 51));
        btnEliminar1.setText("LIMPIAR");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 140, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, 670, 460));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/mapequeño.png"))); // NOI18N
        jLabel7.setText("jLabel4");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 70));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logo_elegance_store_300x125.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 360, 260));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(85, 85, 85));
        jLabel10.setText("Id:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 70, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(85, 85, 85));
        jLabel5.setText("Contraseña:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 120, -1));

        lblRolActual.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblRolActual.setForeground(new java.awt.Color(51, 255, 0));
        jPanel1.add(lblRolActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 540, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -6, 1620, 920));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
      // 1. Obtenemos el modelo de tu tabla actual (ej. Clientes)
    DefaultTableModel modelo = (DefaultTableModel) tblUsuarios.getModel();
    
    // 2. Creamos un ordenador para ese modelo
    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modelo);
    tblUsuarios.setRowSorter(sorter);
    
    // 3. Filtramos usando lo que estás escribiendo en el cuadro de texto
    // El "i" es para que ignore mayúsculas/minúsculas
    sorter.setRowFilter(RowFilter.regexFilter("(?i)" + txtBuscar.getText()));
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
int fila = tblUsuarios.getSelectedRow();
txtId.setText(tblUsuarios.getValueAt(fila, 0).toString());
txtNombre_Completo.setText(tblUsuarios.getValueAt(fila, 1).toString());
txtUsername.setText(tblUsuarios.getValueAt(fila, 2).toString());
txtContrasena.setText(tblUsuarios.getValueAt(fila, 3).toString());
txtRol.setText(tblUsuarios.getValueAt(fila, 4).toString());
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        MenuPrincipal menu = new MenuPrincipal(this.rol, this.nombre);

        // 2. Configuramos la ventana del Menú
        menu.setVisible(true);
        menu.setLocationRelativeTo(null); // Para que salga centrado

        // 3. Cerramos la ventana actual de Productos
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
if (!txtId.getText().isEmpty()) {
    int pregunta = JOptionPane.showConfirmDialog(null, "¿Estás seguro de eliminar este usuario?");
    if (pregunta == 0) {
        int id = Integer.parseInt(txtId.getText());
        uDao.EliminarUsuario(id);
        ListarUsuarios(); // Refresca la tabla
        LimpiarCampos();  // Borra los textos
    }
} else {
    JOptionPane.showMessageDialog(null, "Selecciona un usuario de la tabla");
}
registrarAccion("ELIMINÓ permanentemente al usuario: " + txtUsername.getText());
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
if (!txtUsername.getText().equals("") && !txtContrasena.getText().equals("") && !txtNombre_Completo.getText().equals("")) {
    
    // 1. Llenamos el objeto Usuario con lo que escribiste en los cuadros de texto
    u.setNombreCompleto(txtNombre_Completo.getText());
    u.setUsername(txtUsername.getText());
    u.setContrasena(txtContrasena.getText());
    u.setRol(txtRol.getText());

    // 2. Llamamos al método del DAO para insertar en MySQL
    if (uDao.RegistrarUsuario(u)) {
        JOptionPane.showMessageDialog(null, "¡Usuario Registrado!");
        
        // 3. Limpiamos y actualizamos la tabla para ver el nuevo usuario de una vez
        LimpiarCampos();
        ListarUsuarios(); 
    } else {
        JOptionPane.showMessageDialog(null, "Error al registrar: El usuario ya existe o hay un problema con la base de datos");
    }
} else {
    JOptionPane.showMessageDialog(null, "Por favor, completa todos los campos obligatorios");
}
registrarAccion("Creó un nuevo acceso para el usuario: " + txtUsername.getText());
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar1ActionPerformed
if (txtId.getText().equals("")) {
    JOptionPane.showMessageDialog(null, "Seleccione una fila de la tabla");
} else {
    if (!txtNombre_Completo.getText().equals("") && !txtUsername.getText().equals("")) {
        u.setNombreCompleto(txtNombre_Completo.getText());
        u.setUsername(txtUsername.getText());
        u.setContrasena(txtContrasena.getText());
        u.setRol(txtRol.getText());
        u.setIdUsuario(Integer.parseInt(txtId.getText()));
        
        if (uDao.ModificarUsuario(u)) {
            JOptionPane.showMessageDialog(null, "Usuario Modificado");
            LimpiarCampos();
            ListarUsuarios(); // Para ver los cambios de inmediato
        } else {
            JOptionPane.showMessageDialog(null, "Error al modificar el usuario");
        }
    }
}
registrarAccion("Actualizó los datos/permisos del usuario: " + txtUsername.getText());
    }//GEN-LAST:event_btnModificar1ActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
    txtId.setText("");
    txtNombre_Completo.setText("");
    txtUsername.setText("");
    txtContrasena.setText("");
    txtRol.setText("");
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRolActual;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre_Completo;
    private javax.swing.JTextField txtRol;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
